export const MODIFY_SEARCH = 'MODIFY_SEARCH';
export const FETCH_SEARCH_PENDING = 'FETCH_SEARCH_PENDING';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
export const MODIFY_PRODUCTS = 'MODIFY_PRODUCTS';
