export const MODIFY_SEARCH = 'MODIFY_SEARCH';
export const FETCH_SEARCH_PENDING = 'FETCH_SEARCH_PENDING';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
export const MODIFY_PRODUCTS = 'MODIFY_PRODUCTS';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const MODIFY_CART_ITEMS = 'MODIFY_CART_ITEMS';

export const FETCH_LOGIN_PENDING = 'FETCH_LOGIN_PENDING';
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
export const MODIFY_EMAIL = 'MODIFY_EMAIL';
export const MODIFY_PASSWORD = 'MODIFY_PASSWORD';

export const SET_TOKEN = 'SET_TOKEN';
